package com.sourcekoza.careerpilot.resume.service;

import com.sourcekoza.careerpilot.exception.ResourceNotFoundException;
import com.sourcekoza.careerpilot.resume.domain.Resume;
import com.sourcekoza.careerpilot.resume.domain.ResumeVersion;
import com.sourcekoza.careerpilot.resume.dto.ResumeVersionCreateRequest;
import com.sourcekoza.careerpilot.resume.dto.ResumeVersionResponse;
import com.sourcekoza.careerpilot.resume.mapper.ResumeMapper;
import com.sourcekoza.careerpilot.resume.repository.ResumeRepository;
import com.sourcekoza.careerpilot.resume.repository.ResumeVersionRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

/**
 * Business logic service for Resume Version operations.
 *
 * <p>Manages the creation and retrieval of immutable resume versions.
 * Each version represents a snapshot of the resume content at a specific
 * point in time. Versions are never modified or deleted.</p>
 */
@Service
@Transactional(readOnly = true)
public class ResumeVersionService {

    private static final Logger log = LoggerFactory.getLogger(ResumeVersionService.class);

    private final ResumeRepository resumeRepository;
    private final ResumeVersionRepository resumeVersionRepository;
    private final ResumeMapper resumeMapper;

    public ResumeVersionService(ResumeRepository resumeRepository,
                                ResumeVersionRepository resumeVersionRepository,
                                ResumeMapper resumeMapper) {
        this.resumeRepository = resumeRepository;
        this.resumeVersionRepository = resumeVersionRepository;
        this.resumeMapper = resumeMapper;
    }

    /**
     * Creates a new immutable version for the specified resume.
     *
     * <p>The version number is auto-generated by incrementing the highest
     * existing version number for the resume.</p>
     *
     * @param userId   the authenticated user's ID (for ownership verification)
     * @param resumeId the resume to create a version for
     * @param request  the version creation request containing markdown content
     * @return the created version response
     * @throws ResourceNotFoundException if the resume does not exist or belongs to another user
     */
    @Transactional
    public ResumeVersionResponse createVersion(UUID userId, UUID resumeId, ResumeVersionCreateRequest request) {
        Resume resume = findResumeOrThrow(userId, resumeId);

        int nextVersionNumber = (int) (resumeVersionRepository.countByResumeId(resumeId) + 1);

        ResumeVersion version = ResumeVersion.builder()
                .resume(resume)
                .versionNumber(nextVersionNumber)
                .markdownContent(request.markdownContent())
                .changeSummary(request.changeSummary())
                .build();

        ResumeVersion saved = resumeVersionRepository.save(version);

        log.info("Created version {} for resume {}", nextVersionNumber, resumeId);

        return resumeMapper.toVersionResponse(saved);
    }

    /**
     * Lists all versions for a resume, ordered by version number descending.
     *
     * @param userId   the authenticated user's ID (for ownership verification)
     * @param resumeId the resume to list versions for
     * @return list of version responses
     * @throws ResourceNotFoundException if the resume does not exist or belongs to another user
     */
    public List<ResumeVersionResponse> listVersions(UUID userId, UUID resumeId) {
        findResumeOrThrow(userId, resumeId);
        List<ResumeVersion> versions = resumeVersionRepository.findByResumeIdOrderByVersionNumberDesc(resumeId);
        return versions.stream().map(resumeMapper::toVersionResponse).toList();
    }

    /**
     * Retrieves a specific version by ID, verifying resume ownership.
     *
     * @param userId    the authenticated user's ID (for ownership verification)
     * @param resumeId  the resume the version belongs to
     * @param versionId the version ID to retrieve
     * @return the version response
     * @throws ResourceNotFoundException if the resume or version does not exist
     */
    public ResumeVersionResponse getVersion(UUID userId, UUID resumeId, UUID versionId) {
        findResumeOrThrow(userId, resumeId);
        ResumeVersion version = resumeVersionRepository.findByIdAndResumeId(versionId, resumeId)
                .orElseThrow(() -> new ResourceNotFoundException("ResumeVersion", "id", versionId));
        return resumeMapper.toVersionResponse(version);
    }

    private Resume findResumeOrThrow(UUID userId, UUID resumeId) {
        return resumeRepository.findByIdAndUserIdAndDeletedAtIsNull(resumeId, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Resume", "id", resumeId));
    }
}
