package com.sourcekoza.careerpilot.resume.controller;

import com.sourcekoza.careerpilot.auth.domain.User;
import com.sourcekoza.careerpilot.auth.repository.UserRepository;
import com.sourcekoza.careerpilot.common.ApiResponse;
import com.sourcekoza.careerpilot.resume.dto.ResumeVersionCreateRequest;
import com.sourcekoza.careerpilot.resume.dto.ResumeVersionResponse;
import com.sourcekoza.careerpilot.resume.service.ResumeVersionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.UUID;

/**
 * REST controller for Resume Version operations.
 *
 * <p>Manages the creation and retrieval of immutable resume versions.
 * All endpoints require JWT authentication. Ownership is enforced
 * via the authenticated user's ID.</p>
 */
@RestController
@RequestMapping("/api/v1/resumes/{resumeId}/versions")
@Tag(name = "Resume Version", description = "Resume version management operations")
@SecurityRequirement(name = "bearerAuth")
public class ResumeVersionController {

    private final ResumeVersionService resumeVersionService;
    private final UserRepository userRepository;

    public ResumeVersionController(ResumeVersionService resumeVersionService,
                                   UserRepository userRepository) {
        this.resumeVersionService = resumeVersionService;
        this.userRepository = userRepository;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    @Operation(summary = "Create a new resume version",
            description = "Creates a new immutable version for the specified resume. "
                    + "Version number is auto-generated by the system.")
    public ApiResponse<ResumeVersionResponse> createVersion(
            @PathVariable UUID resumeId,
            @Valid @RequestBody ResumeVersionCreateRequest request) {
        UUID userId = getAuthenticatedUserId();
        ResumeVersionResponse response = resumeVersionService.createVersion(userId, resumeId, request);
        return ApiResponse.success(response, "Resume version created successfully");
    }

    @GetMapping
    @Operation(summary = "List resume versions",
            description = "Returns all versions for a resume, ordered by version number descending")
    public ApiResponse<List<ResumeVersionResponse>> listVersions(@PathVariable UUID resumeId) {
        UUID userId = getAuthenticatedUserId();
        List<ResumeVersionResponse> versions = resumeVersionService.listVersions(userId, resumeId);
        return ApiResponse.success(versions);
    }

    @GetMapping("/{versionId}")
    @Operation(summary = "Get a specific resume version",
            description = "Retrieves a single resume version by its ID")
    public ApiResponse<ResumeVersionResponse> getVersion(
            @PathVariable UUID resumeId,
            @PathVariable UUID versionId) {
        UUID userId = getAuthenticatedUserId();
        ResumeVersionResponse response = resumeVersionService.getVersion(userId, resumeId, versionId);
        return ApiResponse.success(response);
    }

    /**
     * Extracts the authenticated user's UUID from the Spring Security context.
     */
    private UUID getAuthenticatedUserId() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        String email = authentication.getName();
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new UsernameNotFoundException(
                        "User not found with email: " + email));
        return user.getId();
    }
}
