package com.sourcekoza.careerpilot.resume.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request DTO for creating a new resume version.
 *
 * <p>The version number is generated by the system and must not be
 * provided by the client.</p>
 */
public record ResumeVersionCreateRequest(
    @NotBlank(message = "Markdown content is required")
    String markdownContent,

    @Size(max = 500, message = "Change summary must not exceed 500 characters")
    String changeSummary
) {}
